version: v1
replicaCount: 9

image:
  name: booking-service
  tag: v1
  pullPolicy: Never

service:
  create: true

env:
  - name: SERVICE_VERSION
    value: "v1"
  - name: ENABLE_FEATURE_X
    value: "false"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 160Mi

livenessProbe:
  httpGet:
    path: /ping
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ping
    port: 8080
  initialDelaySeconds: 3
  periodSeconds: 5